---
- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/share/fonts
    mode: "0644"
    owner: root
    group: root
  loop: "{{ fonts_files }}"
  notify: Rebuild font cache
