---
- name: Create custom fonts folder
  ansible.builtin.file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  become_user: root

- name: Copy font files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/fonts/"
    dest: /usr/local/share/fonts
    mode: "0644"
    owner: root
    group: root
  loop: "{{ fonts_files }}"
  notify: Rebuild font cache
  become: true
  become_user: root
